services:
  thedb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=catalogoJuegos'
      - 'MONGO_INITDB_ROOT_PASSWORD=vienna'
      - 'MONGO_INITDB_ROOT_USERNAME=bowie'
    ports:
      - '27017:27017'
    volumes:
      - themongo:/data/db
#    networks:
#      - app-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: juegos-app
#    environment:
#      MONGODB_URI: mongodb://bowie:vienna@thedb:27017/catalogoJuegos
#    ports:
#      - "8080:8080"
#    depends_on:
#      - thedb
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge

volumes:
  themongo:
    external: true